spring.application.name=SpringSecEx
spring.security.user.name=yashu
spring.security.user.password=aman
spring.datasource.url=jdbc:postgresql://localhost:5432/Spring
spring.datasource.username=postgres
spring.datasource.password=1947
