spring.application.name=SpringbootLog4j2
#logging.level.com.yashu.SpringbootLog4j2.Controller=debug
#logging.level.com.yashu.SpringbootLog4j2.service=trace
#logging.level.root=trace
logging.pattern.console=%c : %p --> %m :: %d %n
logging.file.name=logger/log.txt
logging.pattern.file=%d: %c : %p --> %m : %M : %n