server:
  port: 8082

spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: yashu-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.yashu.kafka.model
