spring.application.name=simpleWebApp
spring.datasource.url=jdbc:h2:mem:yashu
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
